---
title: "Restricted Gradient Test: Data Example"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
```

```{r}
library(causaldrf)
library(latex2exp)
data("nmes_data")

source('npscore.R')
```



```{r}
w <- model.matrix(~-1 + LASTAGE + AGESMOKE + MALE + educate +
                    marital + SREGION + POVSTALB, data = nmes_data)
set.seed(206)
# w <- model.matrix(~-1 + LASTAGE + AGESMOKE, data = nmes_data)
# w <- model.matrix(~-1 + LASTAGE + AGESMOKE, data = nmes_data)
y <- nmes_data$TOTALEXP
x <- nmes_data$packyears
out.pam <- PAM(y = y, x = log(1 + x), w = w, d = 10, lam.max = 100,
               no.bs = 10000)
```

```{r NMESResults}
plot(out.pam$x0, out.pam$fitted.x0, ylim = c(-2000, 2000), type = "n",
     lty = 2, lwd = 1.5, xlab = "log(pack-years)", ylab = TeX("$\\theta_0$"),
     cex.lab = 1.2)
abline(h = seq(-2000, 2000, 500), v = seq(-5, 5, .5), 
       col = "grey", lwd = .5)
lines(out.pam$x0, out.pam$fitted.x0, lwd = 2, col = "black")
lines(out.pam$x0, out.pam$cb.upper, col = "orange")
lines(out.pam$x0, out.pam$cb.lower, col = "orange")
legend("topleft", paste("P-value = ", out.pam$p.val), bg = "white")
rug(log(nmes_data$packyears + 1))
```

```{r NMESResultsScale}

plot(x = exp(out.pam$x0) - 1, y = out.pam$fitted.x0, ylim = c(-2000, 2000), type = "n",
     lty = 2, lwd = 1.5, xlab = "pack-years", ylab = TeX("$\\theta_0$"),
     cex.lab = 1.2)
abline(h = seq(-2000, 2000, 500), v = seq(0, 300, 25), 
       col = "grey", lwd = .5)
lines(exp(out.pam$x0) - 1, out.pam$fitted.x0, lwd = 2, col = "black")
lines(exp(out.pam$x0) - 1, out.pam$cb.upper, col = "orange")
lines(exp(out.pam$x0) - 1, out.pam$cb.lower, col = "orange")
legend("topleft", paste("P-value = ", out.pam$p.val), bg = "white")
rug(nmes_data$packyears)
```

```{r NMESResultsDist}
plot(log(x + 1), y, xlab = "log(pack-years)", ylab = "Total Expenditure", type = "n")
points(log(x+1), y, pch = 1, col = "grey", cex = .75)
ss <- smooth.spline(log(x+1), y)
lines(ss$x, ss$y, col = "salmon", lwd = 3)
rug(log(x+1))
```